server:
  port: 8180
  tomcat:
    basedir: d:/fileUpload

spring:
  resources:
    #static-locations: classpath:/build/,classpath:/static
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/zhihuigongdi?characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      connection-properties: druid.stat.mergeSql=true
      max-idle: 8
      min-idle: 8
      max-active: 20
      initial-size: 10
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #prefix: classpath:/build/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  #指定环境为测试环境
  profiles:
    active: dev


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath*:mapper/*Mapper.xml
